# Generated by Django 2.2.7 on 2019-11-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AddField(
            model_name='review',
            name='raiting',
            field=models.IntegerField(choices=[(5, 'отлично'), (4, 'хорошо'), (3, 'удовлетворительно'), (2, 'плохо'), (1, 'отвратительно')], null=True, verbose_name='Оценка'),
        ),
    ]
